version: '3.8'

services:
## 開発用
  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: dockerfile.dev
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - .:/app

## 本番用
  # app:
  #   container_name: app
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   tty: true
  #   ports:
  #     - 80:8080
  #   volumes:
  #     - .:/app

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.dockerfile
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "test"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "password"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    networks:
      - default

networks:
  default:
volumes:
  mysql_data: